### ISSUE TITLE
[Functional] prohibit wallet names composed only of spaces (1 or many)

### ISSUE THREAD

**Issue by FSOL-XDAG** [XDagger/XDAG-Pro#10]
When creating (or importing) a wallet, namie it " " permit to press "Continue". This must be prohibit to avoid problems.

![image](https://user-images.githubusercontent.com/128682335/231469786-c4ba98e4-0e9e-4988-bc1f-69d8c0df7826.png)

**Comment by amazingCoding** [comment]
Support has been added in the latest version.
