### ISSUE TITLE
[Cosmetic] Text not clear in french

### ISSUE THREAD

**Issue by FSOL-XDAG** [XDagger/XDAG-Pro#11]
In french, when creating security code, this text is display : 

![image](https://user-images.githubusercontent.com/128682335/231471229-858d6fc2-2a63-4c8b-9e6c-9045cd6c6fad.png)

Should be replace by "Avant de commencer à **utiliser XDAG-Pro**, vous devez définir un **code** pour garantir **sa** sécurité".

Btw, regarding this 6-digit code, it is called password which is inaccurate. It should be called a code. Simply.

**Comment by FSOL-XDAG** [comment]
'password' term have been replace by 'secret code' in [this commit](https://github.com/XDagger/XDAG-Pro/pull/20/commits/891d750b485e8be62e9da4cf2eee8d215671fcbe)

**Comment by amazingCoding** [comment]
[Please direct all translation-related issues here](https://github.com/XDagger/XDAG-Pro/issues/19)

**Comment by FSOL-XDAG** [comment]
👍
