### ISSUE TITLE
[Cosmetic] French / Main screen / Translate pb

### ISSUE THREAD

**Issue by FSOL-XDAG** [XDagger/XDAG-Pro#12]
In french on main screen, the word "Recevoir" (in red square) must be replace by "Revenu". The same one in green square mustn't be change (Recevoir), it's ok.

![image](https://user-images.githubusercontent.com/128682335/231473081-d26e3703-24f7-40ee-93f9-b2973ee3f036.png)

**Comment by FSOL-XDAG** [comment]
I am modifying my request. I am providing more details. There is a confusion in French between infinitive verbs and conjugated verbs. 

The words framed in green should not change. On the other hand, in the red frames, for "Send" you have to put "Sent". For "Receive", you have to put "Received".

![image](https://user-images.githubusercontent.com/128682335/231479450-d3a7686b-0f27-4909-9307-aea92db09c3e.png)

Same thing in English : 

![image](https://user-images.githubusercontent.com/128682335/231480718-64edf022-feec-4709-91f6-aa59f2a4ec76.png)

Send -> Sent
Receive -> Received

**Comment by amazingCoding** [comment]
[Please direct all translation-related issues here](https://github.com/XDagger/XDAG-Pro/issues/19)
