### ISSUE TITLE
[Cosmetic] French / Send XDAG / Upcase 'r' for Remarque

### ISSUE THREAD

**Issue by FSOL-XDAG** [XDagger/XDAG-Pro#13]
Very little improvment : 

![image](https://user-images.githubusercontent.com/128682335/231477960-1b2c1475-5e08-447c-a193-0c7e3442b12c.png)

'r' should be upcase with 'R'.

**Comment by amazingCoding** [comment]
[Please direct all translation-related issues here](https://github.com/XDagger/XDAG-Pro/issues/19)

**Comment by FSOL-XDAG** [comment]
Corrected in v 1.0.10(11).
