### ISSUE TITLE
[Functional] len of remark

### ISSUE THREAD

**Issue by FSOL-XDAG** [XDagger/XDAG-Pro#14]
So send screen : 

![image](https://user-images.githubusercontent.com/128682335/231478513-3e65f498-b4a5-40c9-884a-921a0946c8da.png)

Remark counter seems to be false. With word 'TEST' it should be 4/23, not 5/33.

**Comment by amazingCoding** [comment]
![image](https://user-images.githubusercontent.com/65453513/231593437-013f99ee-0419-4fd6-b69d-c64c017ae104.png)
I tested this function on my side and it works fine.
Please make sure there are no spaces at the end of your input.

**Comment by FSOL-XDAG** [comment]
May be a space after 'test' word. In any case, len max (remark) = 32. Not 33.

**Comment by FSOL-XDAG** [comment]
Works. Perfect. Thanks 👍
