### ISSUE TITLE
[Security] No biometric verification at XDAG-Pro launch

### ISSUE THREAD

**Issue by FSOL-XDAG** [XDagger/XDAG-Pro#15]
No illustration for this outcome.

If you close the program completely and go back to the Android springboard, and restart the application, no biometric identification is requested.

So anyone can launch XDAG-Pro on the smartphone without our knowledge (if our back is turned) and know the balance of our account.

**Comment by amazingCoding** [comment]
The latest version already supports

**Comment by FSOL-XDAG** [comment]
Works. Perfect. Thanks 👍
