### ISSUE TITLE
[Functional] Prohibit self-transfer

### ISSUE THREAD

**Issue by FSOL-XDAG** [XDagger/XDAG-Pro#16]
I can send XDAG to myself. This should be prohibit. This should be filtering by XDAG-Pro before submit to network.

![image](https://user-images.githubusercontent.com/128682335/231487832-48041c7f-2044-4185-9c21-75eea946336c.png)

![image](https://user-images.githubusercontent.com/128682335/231487934-c833f861-8cfb-4675-8cb6-7bec3135fe1e.png)

![image](https://user-images.githubusercontent.com/128682335/231488100-02ca42ae-153e-423d-b024-3af7b0275a2d.png)

**Comment by amazingCoding** [comment]
As the logic of giving the transfer itself is valid. Also RPC supports this, so the client should not disable this.
In this case, I will warn the user in red font in the panel before the transaction. Or I will add a text warning later.
![telegram-cloud-photo-size-5-6188030134246814830-y](https://user-images.githubusercontent.com/65453513/232332370-3ade2c54-9cc1-454f-853b-4754a2086820.jpg)

**Comment by FSOL-XDAG** [comment]
👍
