### ISSUE TITLE
[Functional] Add 'UTC' after tx timstamp to avoid confusion

### ISSUE THREAD

**Issue by FSOL-XDAG** [XDagger/XDAG-Pro#17]
Local hour is different than network time. To avoid confusion, shuld be usefull to add 'UTC' after tx timestamp.

![image](https://user-images.githubusercontent.com/128682335/231489093-def74c38-fb70-4f72-b419-531223b28862.png)

**Comment by amazingCoding** [comment]
Support has been added in the latest version.

**Comment by FSOL-XDAG** [comment]
Great ! Thanks. 

Should UTC on same line than hours ? Because UTC concern it, it's more intuitive. You don't think so ?
