### ISSUE TITLE
[Feature] Send XDAGs to one of my wallets listed in XDAG-Pro

### ISSUE THREAD

**Issue by FSOL-XDAG** [XDagger/XDAG-Pro#22]
When you want to make a XDAG transfet (send XDAG), the contacts list appears, as well as a field to enter an address. 

It would be interesting if the list of wallets declared in XDAG Pro also appeared to pick one of them if you want to transfer funds between your wallets (provided they are on the same network mainnet or testnet).

 This would avoid having to create a specific contact for your wallets to send funds.

**Comment by amazingCoding** [comment]
This feature has been added to the latest version

**Comment by FSOL-XDAG** [comment]
Very happy about your proposal ! 

![image](https://user-images.githubusercontent.com/128682335/234334306-02538411-d62e-43f5-b7af-dd5720066b77.png)

Many thanks !!! 🥇
