### ISSUE TITLE
[Ergonomy] Design proposal for sending XDAG

### ISSUE THREAD

**Issue by FSOL-XDAG** [XDagger/XDAG-Pro#23]
Here is a mock-up of how I imagined a redesign of "Send XDAG" interface.

The goal is to be as "click & play" as possible and easy to understand.

Here is the default screen that uses [the idea proposed here](https://github.com/XDagger/XDAG-Pro/issues/22) to choose a destination address in its contacts, but **also in its wallets**. And if not, to enter manually the exit address.

![image](https://user-images.githubusercontent.com/128682335/232339921-c21ed87e-41b5-4047-ad47-09acbcda7721.png)

A "drop down" menu would appear if you press "My Contacts".

![image](https://user-images.githubusercontent.com/128682335/232339935-73dca10a-8c83-4b5f-8f10-77a844489ac5.png)

Same operation if the user presses "My XDAG wallets". In this case, the top menu is retracted, and if he chooses a wallet, he can press "Continue".

![image](https://user-images.githubusercontent.com/128682335/232339946-19bc088c-5683-4100-9a3c-9c0e1f8c20ec.png)

This is a mock-up, and I would be honored if the developer of XDAG-Pro would like to use it as inspiration for a more intuitive experience of his program.

**Comment by amazingCoding** [comment]
This feature has been added to the latest version
