### ISSUE TITLE
[Mnemonic] Make mnemonic verification less tedious

### ISSUE THREAD

**Issue by FSOL-XDAG** [XDagger/XDAG-Pro#3]
![image](https://user-images.githubusercontent.com/128682335/231454796-136ae766-692e-401a-af32-b1e04f84ed30.png)

Typing the 12 mnemonic words is complicated on a smartphone screen because the virtual keyboard takes up a large part of the screen.

The virtual screen hides a lot of text you have already typed, you don't know where you are anymore.

I propose to randomly ask for 3 words and to make proposals in a combobox (drop-down menu) for each one. So the user will not have to type ALL THE WORDS on the keyboard, but just choose some from a list.

Example:

Word check:

n°2 : correct / cake / enemy / scan / noble
n°4 : strong / long / dumb / impact / squeeze
n°12 : noble / strong / dumb / abstract / scan

In 3 clicks the verification is done, and the process is simpler and less long.

**Comment by FSOL-XDAG** [comment]
Example : 

![Image_20230412164545](https://user-images.githubusercontent.com/128682335/231494620-b27488f1-fba6-4fe6-972c-4f92a5aa0397.jpg)

I can't see words on second line : 

![Image_20230412164538](https://user-images.githubusercontent.com/128682335/231494637-2b1a1e9a-ea02-43e1-8983-5599428b0cc7.jpg)

**Comment by FSOL-XDAG** [comment]
👍

**Comment by amazingCoding** [comment]
This virtual keyboard obscuring issue has been fixed in previous versions, if it is still a problem it is probably due to compatibility issues with third party keyboards.

**Comment by FSOL-XDAG** [comment]
It is not a problem of obscuration (my virtual keyboard uses the dark mode). It's a problem with the location of the mnemonic input field.  

When you click in the mnemonic input box, the box has to go to the top of the screen so you can see what you are typing.
