### ISSUE TITLE
[Functional] Select network when create a wallet

### ISSUE THREAD

**Issue by FSOL-XDAG** [XDagger/XDAG-Pro#5]
Choosing the network in the settings is a nonsense. There is no point in having the same address on testnet or mainnet.

![image](https://user-images.githubusercontent.com/128682335/231460150-e47e61ce-b3b9-48b2-809c-840d3d523012.png)

It is therefore interesting to define when creating the wallet if it is on the mainnet or on the testnet.

![image](https://user-images.githubusercontent.com/128682335/231459829-0785f47d-e5bf-45d4-bc64-71609e4c7695.png)

If XDAG-Pro will eventually be able to manage multiple wallets on a single terminal, it will be much more useful this way.

**Comment by amazingCoding** [comment]
As you can see, all the settings on the Settings page are actually client-side configurations, not blockchain configurations. Setting the network here simply means that the URL requested by the client when requesting RPC is different.

In fact, the wallet address generated by the mnemonic or private key you have does not differentiate between testnet and mainnet.
