### ISSUE TITLE
[Security] Perform a biometric check before validating its deactivation

### ISSUE THREAD

**Issue by FSOL-XDAG** [XDagger/XDAG-Pro#6]
It would seem logical to perform a biometric check before validating the deactivation of this parameter. This will increase security.

![image](https://user-images.githubusercontent.com/128682335/231462433-5fbc3ff5-b2ef-4942-8e12-87f0da9543f9.png)

**Comment by amazingCoding** [comment]
The issue has been fixed in the latest version.

**Comment by FSOL-XDAG** [comment]
Perfect, works ! 👍
