### ISSUE TITLE
[Cosmetic] Control out on screen (french)

### ISSUE THREAD

**Issue by FSOL-XDAG** [XDagger/XDAG-Pro#8]
In french, on security menu, the biometrical control is out of screen.

![image](https://user-images.githubusercontent.com/128682335/231465311-ffeb092c-2a6f-4c9a-bef7-0340c51a7640.png)

The text should be shortened with "Biometric Ctrl" (which is short for "biometric control". It will then be understood that the button after allows to activate or deactivate it.

**Comment by amazingCoding** [comment]
The latest version has addressed issues related to the UI.
For changes in translation wording, please open a dedicated new issue for discussion.
